import { useState, useEffect, useRef } from "react";
import Icon from "@/components/ui/icon";
import type { User, Server, ConsoleLog, DBEntry, ServerFile } from "@/types";
import { getServersByUser, subscribeStore, addCoOwner, removeCoOwner, updateServer } from "@/store";

type SideTab = "console" | "files" | "settings" | "coowners" | "database" | "subdomains" | "profile";

const STARTUP_LOGS: ConsoleLog[] = [
  { time: "", type: "info", text: "Hosting-Minecraft: Сервер запускается..." },
  { time: "", type: "info", text: "[Server] Loading libraries, please wait..." },
  { time: "", type: "info", text: "[Server] Starting minecraft server version 1.20.1" },
  { time: "", type: "success", text: "[Server] Loading properties" },
  { time: "", type: "info", text: "[Server] Default game type: SURVIVAL" },
  { time: "", type: "info", text: "[Server] Generating keypair" },
  { time: "", type: "info", text: "[Server] Starting Minecraft server on *:25565" },
  { time: "", type: "success", text: "[Server] Using epoll channel type" },
  { time: "", type: "info", text: "[Server] Preparing level 'world'" },
  { time: "", type: "info", text: "[Server] Preparing start region for dimension minecraft:overworld" },
  { time: "", type: "info", text: "[Server] Time elapsed: 2341 ms" },
  { time: "", type: "success", text: "[Server] Done (3.141s)! For help, type 'help'" },
  { time: "", type: "success", text: "Hosting-Minecraft: Сервер успешно запущен" },
];

const STOP_LOGS: ConsoleLog[] = [
  { time: "", type: "warn", text: "Hosting-Minecraft: Остановка сервера..." },
  { time: "", type: "info", text: "[Server] Stopping the server" },
  { time: "", type: "info", text: "[Server] Saving worlds..." },
  { time: "", type: "info", text: "[Server] Saving chunks for level 'ServerLevel[world]'" },
  { time: "", type: "error", text: "Hosting-Minecraft: Сервер помечен как выключенный" },
];

const defaultFiles: ServerFile[] = [
  { name: "server.jar", type: "jar", size: "42.1 MB" },
  { name: "server.properties", type: "yml", size: "3.2 KB" },
  { name: "eula.txt", type: "txt", size: "1 KB" },
  { name: "ops.json", type: "json", size: "512 B" },
  { name: "whitelist.json", type: "json", size: "256 B" },
  { name: "banned-players.json", type: "json", size: "128 B" },
];

const defaultServerProps = `#Minecraft server properties
#Generated by ZetixHosting
level-name=world
gamemode=survival
difficulty=normal
max-players=20
pvp=true
server-port=25565
server-ip=
enable-command-block=false
spawn-protection=16
online-mode=true
view-distance=10
motd=A Minecraft Server`;

function getTime() {
  return new Date().toLocaleTimeString("ru-RU", { hour: "2-digit", minute: "2-digit", second: "2-digit" });
}

function fileIcon(type: ServerFile["type"]) {
  switch (type) {
    case "jar": return "Package";
    case "jpg": case "png": return "Image";
    case "json": return "Braces";
    case "yml": return "Settings";
    case "txt": return "FileText";
    default: return "File";
  }
}

// ===================== CONSOLE =====================
function ConsoleView({ server, onStatusChange }: { server: Server; onStatusChange: (s: Server["status"]) => void }) {
  const [logs, setLogs] = useState<ConsoleLog[]>([
    { time: getTime(), type: "error", text: "Hosting-Minecraft: Сервер помечен как выключенный" }
  ]);
  const [input, setInput] = useState("");
  const [status, setStatus] = useState<Server["status"]>(server.status);
  const bottomRef = useRef<HTMLDivElement>(null);
  const logIntervalRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [logs]);

  const addLog = (log: ConsoleLog) => {
    setLogs(prev => [...prev, { ...log, time: getTime() }]);
  };

  const startServer = () => {
    if (status === "starting" || status === "active") return;
    setStatus("starting");
    onStatusChange("starting");
    let i = 0;
    const run = () => {
      if (i < STARTUP_LOGS.length) {
        addLog(STARTUP_LOGS[i]);
        i++;
        logIntervalRef.current = setTimeout(run, 180 + Math.random() * 200);
      } else {
        setStatus("active");
        onStatusChange("active");
      }
    };
    run();
  };

  const stopServer = () => {
    if (status === "stopped") return;
    setStatus("stopped");
    onStatusChange("stopped");
    STOP_LOGS.forEach((log, i) => {
      setTimeout(() => addLog(log), i * 200);
    });
  };

  const restartServer = () => {
    stopServer();
    setTimeout(() => startServer(), STOP_LOGS.length * 200 + 500);
  };

  const sendCmd = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) return;
    addLog({ time: getTime(), type: "info", text: `> ${input}` });
    const cmd = input.toLowerCase().trim();
    if (cmd === "help") {
      addLog({ time: getTime(), type: "success", text: "Доступные команды: help, list, stop, restart, say <msg>" });
    } else if (cmd === "list") {
      addLog({ time: getTime(), type: "info", text: "Игроков онлайн: 0/20" });
    } else if (cmd.startsWith("say ")) {
      addLog({ time: getTime(), type: "success", text: `[Server] ${cmd.slice(4)}` });
    } else {
      addLog({ time: getTime(), type: "warn", text: `Неизвестная команда: ${input}` });
    }
    setInput("");
  };

  const logColor: Record<ConsoleLog["type"], string> = {
    info: "#a0aec0",
    warn: "#f6e05e",
    error: "#fc8181",
    success: "#68d391",
  };

  return (
    <div className="flex flex-col h-full">
      {/* Control buttons */}
      <div className="flex items-center gap-3 mb-4 flex-shrink-0">
        <div className="flex items-center gap-2">
          <span className={`w-2.5 h-2.5 rounded-full ${status === "active" ? "bg-green-400 animate-pulse" : status === "starting" ? "bg-yellow-400 animate-pulse" : "bg-red-500"}`}></span>
          <span className="text-white/50 text-sm">{status === "active" ? "Запущен" : status === "starting" ? "Запускается..." : "Остановлен"}</span>
        </div>
        <div className="flex-1" />
        <button onClick={startServer} disabled={status === "active" || status === "starting"}
          className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold transition-all disabled:opacity-40"
          style={{ background: "rgba(34,197,94,0.15)", border: "1px solid rgba(34,197,94,0.3)", color: "#4ade80" }}>
          <Icon name="Play" size={14} /> Старт
        </button>
        <button onClick={stopServer} disabled={status === "stopped"}
          className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold transition-all disabled:opacity-40"
          style={{ background: "rgba(239,68,68,0.15)", border: "1px solid rgba(239,68,68,0.3)", color: "#f87171" }}>
          <Icon name="Square" size={14} /> Стоп
        </button>
        <button onClick={restartServer}
          className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold transition-all"
          style={{ background: "rgba(251,191,36,0.15)", border: "1px solid rgba(251,191,36,0.3)", color: "#fbbf24" }}>
          <Icon name="RotateCcw" size={14} /> Рестарт
        </button>
      </div>

      {/* Console output */}
      <div className="flex-1 rounded-xl overflow-hidden flex flex-col" style={{ background: "#1a1f2e", border: "1px solid rgba(255,255,255,0.06)" }}>
        <div className="flex items-center gap-2 px-4 py-2 border-b border-white/5" style={{ background: "#151923" }}>
          <div className="w-3 h-3 rounded-full bg-red-500/70"></div>
          <div className="w-3 h-3 rounded-full bg-yellow-500/70"></div>
          <div className="w-3 h-3 rounded-full bg-green-500/70"></div>
          <span className="text-white/30 text-xs ml-2 font-mono">console</span>
        </div>
        <div className="flex-1 overflow-y-auto p-4 font-mono text-sm" style={{ minHeight: 0 }}>
          {logs.map((log, i) => (
            <div key={i} className="flex gap-2 mb-0.5 leading-5">
              <span style={{ color: "#4a5568", flexShrink: 0, fontSize: "11px", marginTop: "1px" }}>{log.time}</span>
              <span style={{ color: logColor[log.type], wordBreak: "break-all" }}>{log.text}</span>
            </div>
          ))}
          <div ref={bottomRef} />
        </div>
        <form onSubmit={sendCmd} className="flex gap-2 p-3 border-t border-white/5">
          <span className="text-green-400 font-mono text-sm self-center">{">"}</span>
          <input value={input} onChange={e => setInput(e.target.value)}
            placeholder="Введите команду..."
            disabled={status !== "active"}
            className="flex-1 bg-transparent text-white font-mono text-sm focus:outline-none placeholder-white/20 disabled:opacity-40"
          />
          <button type="submit" disabled={status !== "active"}
            className="text-green-400 hover:text-green-300 disabled:opacity-40">
            <Icon name="Send" size={15} />
          </button>
        </form>
      </div>
    </div>
  );
}

// ===================== MONITORING =====================
function MonitoringBar({ label, value, max, color }: { label: string; value: number; max: number; color: string }) {
  const pct = Math.min(100, (value / max) * 100);
  return (
    <div className="mb-4">
      <div className="flex justify-between mb-1">
        <span className="text-white/60 text-sm">{label}</span>
        <span className="text-white text-sm font-semibold">{value}/{max}</span>
      </div>
      <div className="h-2 rounded-full bg-white/10 overflow-hidden">
        <div className="h-full rounded-full transition-all duration-1000" style={{ width: `${pct}%`, background: color }}></div>
      </div>
    </div>
  );
}

// ===================== FILES =====================
function FilesView() {
  const [files, setFiles] = useState<ServerFile[]>(defaultFiles);
  const [viewing, setViewing] = useState<string | null>(null);
  const [editContent, setEditContent] = useState(defaultServerProps);
  const inputRef = useRef<HTMLInputElement>(null);

  const deleteFile = (name: string) => setFiles(f => f.filter(x => x.name !== name));

  const uploadFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const ext = file.name.split(".").pop()?.toLowerCase() || "other";
    const type: ServerFile["type"] = (["jar", "jpg", "png", "txt", "json", "yml"].includes(ext) ? ext : "other") as ServerFile["type"];
    setFiles(f => [...f, { name: file.name, type, size: `${(file.size / 1024).toFixed(1)} KB` }]);
    e.target.value = "";
  };

  return (
    <div className="h-full flex flex-col">
      <div className="flex items-center justify-between mb-4 flex-shrink-0">
        <h3 className="text-white font-bold font-montserrat">Файлы сервера</h3>
        <button onClick={() => inputRef.current?.click()}
          className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-white btn-primary">
          <Icon name="Upload" size={14} /> Загрузить
        </button>
        <input ref={inputRef} type="file" accept=".jar,.jpg,.jpeg,.png,.txt,.json,.yml,.yaml,.properties" className="hidden" onChange={uploadFile} />
      </div>

      {viewing ? (
        <div className="flex-1 flex flex-col">
          <div className="flex items-center gap-3 mb-3">
            <button onClick={() => setViewing(null)} className="text-white/50 hover:text-white"><Icon name="ArrowLeft" size={16} /></button>
            <span className="text-white font-mono text-sm">{viewing}</span>
          </div>
          <textarea value={editContent} onChange={e => setEditContent(e.target.value)}
            className="flex-1 bg-[#1a1f2e] border border-white/10 rounded-xl p-4 text-white font-mono text-sm resize-none focus:outline-none focus:border-green-500"
          />
          <button onClick={() => setViewing(null)} className="mt-3 btn-primary px-6 py-2 rounded-xl text-white font-semibold text-sm self-end">
            Сохранить
          </button>
        </div>
      ) : (
        <div className="flex-1 overflow-y-auto">
          <div className="space-y-2">
            {files.map(f => (
              <div key={f.name} className="flex items-center gap-3 px-4 py-3 rounded-xl gradient-card hover:bg-white/5 transition-colors">
                <Icon name={fileIcon(f.type)} size={18} className="text-green-400 flex-shrink-0" />
                <span className="text-white text-sm flex-1 font-mono">{f.name}</span>
                <span className="text-white/30 text-xs">{f.size}</span>
                <button onClick={() => { setViewing(f.name); setEditContent(defaultServerProps); }}
                  className="text-white/40 hover:text-green-400 transition-colors ml-1">
                  <Icon name="Eye" size={15} />
                </button>
                <button onClick={() => deleteFile(f.name)}
                  className="text-white/40 hover:text-red-400 transition-colors">
                  <Icon name="Trash2" size={15} />
                </button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ===================== SETTINGS =====================
function SettingsView({ server }: { server: Server }) {
  const [props, setProps] = useState({
    serverName: "My Minecraft Server",
    gamemode: "survival",
    difficulty: "normal",
    maxPlayers: "20",
    pvp: true,
    onlineMode: true,
    viewDistance: "10",
    motd: "A Minecraft Server",
  });

  return (
    <div className="h-full overflow-y-auto">
      <h3 className="text-white font-bold font-montserrat mb-6">Настройки сервера</h3>
      <div className="space-y-6">
        <div className="gradient-card rounded-xl p-5">
          <h4 className="text-white/60 text-xs uppercase tracking-wider mb-4">Основные</h4>
          <div className="grid grid-cols-1 gap-4">
            <div>
              <label className="text-white/50 text-xs mb-1 block">MOTD (описание)</label>
              <input value={props.motd} onChange={e => setProps(p => ({ ...p, motd: e.target.value }))}
                className="w-full px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm focus:outline-none focus:border-green-500" />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-white/50 text-xs mb-1 block">Режим игры</label>
                <select value={props.gamemode} onChange={e => setProps(p => ({ ...p, gamemode: e.target.value }))}
                  className="w-full px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm focus:outline-none focus:border-green-500">
                  <option value="survival">Выживание</option>
                  <option value="creative">Творчество</option>
                  <option value="adventure">Приключение</option>
                  <option value="spectator">Наблюдатель</option>
                </select>
              </div>
              <div>
                <label className="text-white/50 text-xs mb-1 block">Сложность</label>
                <select value={props.difficulty} onChange={e => setProps(p => ({ ...p, difficulty: e.target.value }))}
                  className="w-full px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm focus:outline-none focus:border-green-500">
                  <option value="peaceful">Мирная</option>
                  <option value="easy">Лёгкая</option>
                  <option value="normal">Нормальная</option>
                  <option value="hard">Сложная</option>
                </select>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="text-white/50 text-xs mb-1 block">Макс. игроков</label>
                <input type="number" value={props.maxPlayers} onChange={e => setProps(p => ({ ...p, maxPlayers: e.target.value }))}
                  className="w-full px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm focus:outline-none focus:border-green-500" />
              </div>
              <div>
                <label className="text-white/50 text-xs mb-1 block">Дальность прорисовки</label>
                <input type="number" value={props.viewDistance} onChange={e => setProps(p => ({ ...p, viewDistance: e.target.value }))}
                  className="w-full px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm focus:outline-none focus:border-green-500" />
              </div>
            </div>
          </div>
        </div>
        <div className="gradient-card rounded-xl p-5">
          <h4 className="text-white/60 text-xs uppercase tracking-wider mb-4">Безопасность</h4>
          <div className="flex flex-col gap-3">
            {[
              { key: "pvp", label: "PvP (урон игрок-игрок)" },
              { key: "onlineMode", label: "Онлайн-режим (лицензия)" },
            ].map(item => (
              <div key={item.key} className="flex items-center justify-between">
                <span className="text-white/70 text-sm">{item.label}</span>
                <button onClick={() => setProps(p => ({ ...p, [item.key]: !p[item.key as keyof typeof p] }))}
                  className="relative w-12 h-6 rounded-full transition-all duration-200"
                  style={{ background: props[item.key as keyof typeof props] ? "#22c55e" : "#374151" }}>
                  <span className="absolute top-1 w-4 h-4 rounded-full bg-white transition-all duration-200"
                    style={{ left: props[item.key as keyof typeof props] ? "28px" : "4px" }}></span>
                </button>
              </div>
            ))}
          </div>
        </div>
        <div className="gradient-card rounded-xl p-5">
          <h4 className="text-white/60 text-xs uppercase tracking-wider mb-3">IP адрес сервера</h4>
          <div className="flex items-center gap-3 bg-black/30 rounded-lg px-4 py-3">
            <Icon name="Globe" size={16} className="text-green-400" />
            <span className="text-white font-mono text-sm">{server.ip}:{server.port}</span>
          </div>
        </div>
        <button className="btn-primary px-6 py-3 rounded-xl text-white font-semibold text-sm w-full">
          Сохранить настройки
        </button>
      </div>
    </div>
  );
}

// ===================== CO-OWNERS =====================
function CoOwnersView({ server }: { server: Server }) {
  const [, forceUpdate] = useState(0);
  const [email, setEmail] = useState("");
  const [error, setError] = useState("");

  useEffect(() => subscribeStore(() => forceUpdate(n => n + 1)), []);

  const add = () => {
    if (!email || !/\S+@\S+\.\S+/.test(email)) { setError("Введите корректный email"); return; }
    addCoOwner(server.id, email);
    setEmail("");
    setError("");
  };

  return (
    <div className="h-full overflow-y-auto">
      <h3 className="text-white font-bold font-montserrat mb-6">Совладельцы</h3>
      <div className="gradient-card rounded-xl p-5 mb-4">
        <label className="text-white/50 text-xs mb-2 block">Добавить по email</label>
        <div className="flex gap-2">
          <input value={email} onChange={e => setEmail(e.target.value)} placeholder="friend@email.com"
            className="flex-1 px-3 py-2.5 rounded-xl bg-white/5 border border-white/10 text-white text-sm focus:outline-none focus:border-green-500" />
          <button onClick={add} className="btn-primary px-4 py-2 rounded-xl text-white text-sm font-semibold">
            <Icon name="UserPlus" size={15} />
          </button>
        </div>
        {error && <p className="text-red-400 text-xs mt-1">{error}</p>}
      </div>
      <div className="space-y-2">
        {server.coOwners.length === 0 ? (
          <p className="text-white/30 text-sm text-center py-8">Нет совладельцев</p>
        ) : (
          server.coOwners.map(e => (
            <div key={e} className="flex items-center gap-3 px-4 py-3 rounded-xl gradient-card">
              <Icon name="User" size={16} className="text-green-400" />
              <span className="text-white text-sm flex-1">{e}</span>
              <button onClick={() => removeCoOwner(server.id, e)} className="text-white/40 hover:text-red-400 transition-colors">
                <Icon name="X" size={15} />
              </button>
            </div>
          ))
        )}
      </div>
    </div>
  );
}

// ===================== DATABASE =====================
function DatabaseView() {
  const [entries, setEntries] = useState<DBEntry[]>([
    { id: "1", key: "server_version", value: "1.20.1" },
    { id: "2", key: "max_players", value: "20" },
    { id: "3", key: "spawn_world", value: "world" },
  ]);
  const [newKey, setNewKey] = useState("");
  const [newVal, setNewVal] = useState("");

  const add = () => {
    if (!newKey || !newVal) return;
    setEntries(e => [...e, { id: Date.now().toString(), key: newKey, value: newVal }]);
    setNewKey(""); setNewVal("");
  };

  return (
    <div className="h-full overflow-y-auto">
      <h3 className="text-white font-bold font-montserrat mb-6">База данных</h3>
      <div className="gradient-card rounded-xl p-5 mb-4">
        <div className="flex gap-2">
          <input value={newKey} onChange={e => setNewKey(e.target.value)} placeholder="Ключ"
            className="flex-1 px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm focus:outline-none focus:border-green-500" />
          <input value={newVal} onChange={e => setNewVal(e.target.value)} placeholder="Значение"
            className="flex-1 px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm focus:outline-none focus:border-green-500" />
          <button onClick={add} className="btn-primary px-4 py-2 rounded-lg text-white text-sm font-semibold">
            <Icon name="Plus" size={15} />
          </button>
        </div>
      </div>
      <div className="space-y-2">
        {entries.map(e => (
          <div key={e.id} className="flex items-center gap-3 px-4 py-3 rounded-xl gradient-card">
            <Icon name="Database" size={14} className="text-blue-400" />
            <span className="text-white/60 text-sm font-mono flex-1">{e.key}</span>
            <span className="text-white text-sm font-mono">{e.value}</span>
            <button onClick={() => setEntries(en => en.filter(x => x.id !== e.id))} className="text-white/30 hover:text-red-400 transition-colors">
              <Icon name="Trash2" size={14} />
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}

// ===================== SUBDOMAINS =====================
function SubdomainsView({ server }: { server: Server }) {
  const [subs, setSubs] = useState([`${server.subdomain}.zetixhost.me`]);
  const [input, setInput] = useState("");

  const add = () => {
    if (!input) return;
    setSubs(s => [...s, input.endsWith(".zetixhost.me") ? input : `${input}.zetixhost.me`]);
    setInput("");
  };

  return (
    <div className="h-full overflow-y-auto">
      <h3 className="text-white font-bold font-montserrat mb-6">Субдомены</h3>
      <div className="gradient-card rounded-xl p-5 mb-4">
        <div className="flex gap-2 items-center">
          <input value={input} onChange={e => setInput(e.target.value)} placeholder="my-server"
            className="flex-1 px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm focus:outline-none focus:border-green-500" />
          <span className="text-white/30 text-sm">.zetixhost.me</span>
          <button onClick={add} className="btn-primary px-4 py-2 rounded-lg text-white text-sm font-semibold">
            <Icon name="Plus" size={15} />
          </button>
        </div>
      </div>
      <div className="space-y-2">
        {subs.map((s, i) => (
          <div key={s} className="flex items-center gap-3 px-4 py-3 rounded-xl gradient-card">
            <Icon name="Globe" size={14} className="text-purple-400" />
            <span className="text-white text-sm font-mono flex-1">{s}</span>
            {i > 0 && (
              <button onClick={() => setSubs(ss => ss.filter(x => x !== s))} className="text-white/30 hover:text-red-400 transition-colors">
                <Icon name="Trash2" size={14} />
              </button>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

// ===================== PROFILE =====================
function ProfileView({ user, onLogout }: { user: User; onLogout: () => void }) {
  return (
    <div className="h-full overflow-y-auto">
      <h3 className="text-white font-bold font-montserrat mb-6">Профиль</h3>
      <div className="gradient-card rounded-xl p-6 mb-4">
        <div className="flex items-center gap-4 mb-5">
          <div className="w-16 h-16 rounded-2xl flex items-center justify-center text-2xl font-bold text-white"
            style={{ background: "linear-gradient(135deg,#22c55e,#16a34a)" }}>
            {user.email[0].toUpperCase()}
          </div>
          <div>
            <div className="text-white font-bold text-lg">{user.email.split("@")[0]}</div>
            <div className="text-white/40 text-sm">{user.email}</div>
            {user.isAdmin && <span className="text-xs bg-red-500/20 text-red-400 border border-red-500/30 px-2 py-0.5 rounded-full mt-1 inline-block">Администратор</span>}
          </div>
        </div>
        <div className="grid grid-cols-2 gap-3">
          {[
            { label: "Email", value: user.email },
            { label: "Статус", value: "Активен" },
            { label: "Серверов", value: "1" },
            { label: "Аккаунт", value: user.isAdmin ? "Admin" : "Пользователь" },
          ].map(item => (
            <div key={item.label} className="bg-white/5 rounded-xl p-3">
              <div className="text-white/40 text-xs mb-1">{item.label}</div>
              <div className="text-white text-sm font-semibold">{item.value}</div>
            </div>
          ))}
        </div>
      </div>
      <button onClick={onLogout} className="flex items-center gap-2 px-5 py-3 rounded-xl text-red-400 text-sm font-semibold"
        style={{ background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.2)" }}>
        <Icon name="LogOut" size={15} /> Выйти из аккаунта
      </button>
    </div>
  );
}

// ===================== SERVER PANEL =====================
export default function ServerPanel({ user, onBack, onLogout }: { user: User; onBack: () => void; onLogout: () => void }) {
  const [, forceUpdate] = useState(0);
  const [activeTab, setActiveTab] = useState<SideTab>("console");
  const [selectedServerId, setSelectedServerId] = useState<string | null>(null);
  const [serverStatus, setServerStatus] = useState<Record<string, Server["status"]>>({});

  useEffect(() => subscribeStore(() => forceUpdate(n => n + 1)), []);

  const servers = getServersByUser(user.email);
  const selectedServer = servers.find(s => s.id === selectedServerId) || servers[0] || null;

  const sideItems: { key: SideTab; icon: string; label: string }[] = [
    { key: "console", icon: "Terminal", label: "Консоль" },
    { key: "files", icon: "FolderOpen", label: "Файлы" },
    { key: "settings", icon: "Settings", label: "Настройки" },
    { key: "coowners", icon: "Users", label: "Совладельцы" },
    { key: "database", icon: "Database", label: "База данных" },
    { key: "subdomains", icon: "Globe", label: "Субдомены" },
    { key: "profile", icon: "User", label: "Профиль" },
  ];

  // Monitoring stats (simulated real-time)
  const [cpu, setCpu] = useState(12);
  const [ram, setRam] = useState(256);
  const status = selectedServer ? (serverStatus[selectedServer.id] || selectedServer.status) : "stopped";

  useEffect(() => {
    const t = setInterval(() => {
      if (status === "active") {
        setCpu(Math.floor(10 + Math.random() * 40));
        setRam(Math.floor(200 + Math.random() * 400));
      }
    }, 2000);
    return () => clearInterval(t);
  }, [status]);

  const handleStatusChange = (s: Server["status"]) => {
    if (!selectedServer) return;
    setServerStatus(prev => ({ ...prev, [selectedServer.id]: s }));
  };

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white flex flex-col">
      {/* Top Bar */}
      <div className="flex items-center gap-4 px-6 py-3 border-b border-white/5 flex-shrink-0"
        style={{ background: "rgba(10,10,10,0.95)", backdropFilter: "blur(16px)" }}>
        <button onClick={onBack} className="text-white/50 hover:text-white transition-colors">
          <Icon name="ArrowLeft" size={20} />
        </button>
        <span className="font-extrabold font-montserrat">Zetix<span className="text-green-400">Hosting</span></span>
        <div className="h-4 w-px bg-white/10"></div>
        <span className="text-white/40 text-sm">Панель управления</span>
        <div className="flex-1" />

        {/* Server selector */}
        {servers.length > 1 && (
          <select value={selectedServerId || ""} onChange={e => setSelectedServerId(e.target.value)}
            className="bg-white/5 border border-white/10 text-white text-sm px-3 py-1.5 rounded-lg focus:outline-none">
            {servers.map(s => <option key={s.id} value={s.id}>{s.planEmoji} {s.planName}</option>)}
          </select>
        )}

        <span className="text-white/40 text-sm hidden md:block">{user.email}</span>
      </div>

      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        <div className="w-56 flex-shrink-0 border-r border-white/5 flex flex-col" style={{ background: "#0d0d0d" }}>
          {selectedServer && (
            <div className="p-4 border-b border-white/5">
              <div className="text-xs text-white/40 mb-1 uppercase tracking-wider">Сервер</div>
              <div className="flex items-center gap-2">
                <span className="text-lg">{selectedServer.planEmoji}</span>
                <div>
                  <div className="text-white text-sm font-bold font-montserrat">{selectedServer.planName}</div>
                  <div className="text-white/30 text-xs font-mono">{selectedServer.ip}:{selectedServer.port}</div>
                </div>
              </div>
            </div>
          )}

          <nav className="flex-1 p-2 overflow-y-auto">
            {sideItems.map(item => (
              <button key={item.key} onClick={() => setActiveTab(item.key)}
                className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all duration-150 mb-0.5"
                style={{
                  background: activeTab === item.key ? "rgba(34,197,94,0.12)" : "transparent",
                  color: activeTab === item.key ? "#4ade80" : "rgba(255,255,255,0.5)",
                  borderLeft: activeTab === item.key ? "2px solid #22c55e" : "2px solid transparent",
                }}>
                <Icon name={item.icon} size={16} />
                {item.label}
              </button>
            ))}
          </nav>

          {/* Monitoring mini */}
          {selectedServer && (
            <div className="p-4 border-t border-white/5">
              <div className="text-xs text-white/40 uppercase tracking-wider mb-3">Мониторинг</div>
              <MonitoringBar label="CPU" value={status === "active" ? cpu : 0} max={100} color="#22c55e" />
              <MonitoringBar label="RAM (МБ)" value={status === "active" ? ram : 0} max={1024} color="#3b82f6" />
              <div className="text-xs text-white/30 mt-2">
                <span className={`w-2 h-2 rounded-full inline-block mr-1 ${status === "active" ? "bg-green-400" : "bg-red-500"}`}></span>
                {status === "active" ? "Online" : status === "starting" ? "Starting..." : "Offline"}
              </div>
            </div>
          )}
        </div>

        {/* Main content */}
        <div className="flex-1 overflow-hidden p-6">
          {!selectedServer ? (
            <div className="h-full flex items-center justify-center flex-col gap-4 text-center">
              <div className="text-6xl">🖥</div>
              <h2 className="text-xl font-bold text-white font-montserrat">Нет активных серверов</h2>
              <p className="text-white/40 text-sm max-w-xs">Купите тариф на главной странице, после подтверждения администратором сервер появится здесь</p>
              <button onClick={onBack} className="btn-primary px-6 py-3 rounded-xl text-white font-semibold">
                Перейти к тарифам
              </button>
            </div>
          ) : (
            <div className="h-full">
              {activeTab === "console" && <ConsoleView server={selectedServer} onStatusChange={handleStatusChange} />}
              {activeTab === "files" && <FilesView />}
              {activeTab === "settings" && <SettingsView server={selectedServer} />}
              {activeTab === "coowners" && <CoOwnersView server={selectedServer} />}
              {activeTab === "database" && <DatabaseView />}
              {activeTab === "subdomains" && <SubdomainsView server={selectedServer} />}
              {activeTab === "profile" && <ProfileView user={user} onLogout={onLogout} />}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
